In [2]:
from sklearn.datasets import load_boston

data = load_boston()
# 特征数据
X = data.data
# 目标数据
y = data.target

e:\soft\anaconda3\envs\ai0910\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing data

In [4]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [5]:
from sklearn.datasets import load_iris
data = load_iris() # 加载鸢尾花数据
X = data.data  # 获取到特征数据
y = data.target # 获取到目标数据
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
import pandas as pd
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [7]:
# 获取数据
df = sns.load_dataset('titanic')

# 设置显示所有的的列 jupyter
pd.set_option('display.max_columns', None)

# 输出数据集
print(df.head(30))

    survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
0          0       3    male  22.0      1      0    7.2500        S   Third   
1          1       1  female  38.0      1      0   71.2833        C   First   
2          1       3  female  26.0      0      0    7.9250        S   Third   
3          1       1  female  35.0      1      0   53.1000        S   First   
4          0       3    male  35.0      0      0    8.0500        S   Third   
5          0       3    male   NaN      0      0    8.4583        Q   Third   
6          0       1    male  54.0      0      0   51.8625        S   First   
7          0       3    male   2.0      3      1   21.0750        S   Third   
8          1       3  female  27.0      0      2   11.1333        S   Third   
9          1       2  female  14.0      1      0   30.0708        C  Second   
10         1       3  female   4.0      1      1   16.7000        S   Third   
11         1       1  female  58.0      0      0   2

In [8]:
# 处理冗余数据
df.drop(columns=['class'], inplace=True)
df.drop(columns=['alive'], inplace=True)
df.drop(columns=['embarked'], inplace=True)

In [9]:
df

survived  pclass     sex   age  sibsp  parch     fare    who  adult_male  \
0           0       3    male  22.0      1      0   7.2500    man        True   
1           1       1  female  38.0      1      0  71.2833  woman       False   
2           1       3  female  26.0      0      0   7.9250  woman       False   
3           1       1  female  35.0      1      0  53.1000  woman       False   
4           0       3    male  35.0      0      0   8.0500    man        True   
..        ...     ...     ...   ...    ...    ...      ...    ...         ...   
886         0       2    male  27.0      0      0  13.0000    man        True   
887         1       1  female  19.0      0      0  30.0000  woman       False   
888         0       3  female   NaN      1      2  23.4500  woman       False   
889         1       1    male  26.0      0      0  30.0000    man        True   
890         0       3    male  32.0      0      0   7.7500    man        True   

    deck  embark_town  alone  
0    NaN  Southampton  False  
1      C    Cherbourg  False  
2    NaN  Southampton   True  
3      C  Southampton  False  
4    NaN  Southampton   True  
..   ...          ...    ...  
886  NaN  Southampton   True  
887    B  Southampton   True  
888  NaN  Southampton  False  
889    C    Cherbourg   True  
890  NaN   Queenstown   True  

[891 rows x 12 columns]

In [10]:
# 统计缺失值情况
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
who              0
adult_male       0
deck           688
embark_town      2
alone            0
dtype: int64


In [11]:
# 处理缺失值 - 使用均值填充 age（年龄）列的缺失值
imputer = SimpleImputer(strategy='mean')
df['age'] = imputer.fit_transform(df[['age']])

In [12]:
# 处理缺失值 - 使用众数填充 embark_town（登录港口）列的缺失值
imputer = SimpleImputer(strategy='most_frequent')
df['embark_town'] = imputer.fit_transform(df[['embark_town']])

ValueError: 2

In [13]:
df[['embark_town']]

embark_town
0    Southampton
1      Cherbourg
2    Southampton
3    Southampton
4    Southampton
..           ...
886  Southampton
887  Southampton
888  Southampton
889    Cherbourg
890   Queenstown

[891 rows x 1 columns]

In [15]:
df['embark_town'].dropna()

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...     
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 889, dtype: object

In [16]:
df.drop(columns=['deck'], inplace=True)

In [17]:
# 处理类别特征 - 使用 LabelEncoder 对 adult_male（成人男性）进行整数编码
label_encoder = LabelEncoder()
df['adult_male'] = label_encoder.fit_transform(df['adult_male'])

In [18]:
df

survived  pclass     sex        age  sibsp  parch     fare    who  \
0           0       3    male  22.000000      1      0   7.2500    man   
1           1       1  female  38.000000      1      0  71.2833  woman   
2           1       3  female  26.000000      0      0   7.9250  woman   
3           1       1  female  35.000000      1      0  53.1000  woman   
4           0       3    male  35.000000      0      0   8.0500    man   
..        ...     ...     ...        ...    ...    ...      ...    ...   
886         0       2    male  27.000000      0      0  13.0000    man   
887         1       1  female  19.000000      0      0  30.0000  woman   
888         0       3  female  29.699118      1      2  23.4500  woman   
889         1       1    male  26.000000      0      0  30.0000    man   
890         0       3    male  32.000000      0      0   7.7500    man   

     adult_male  embark_town  alone  
0             1  Southampton  False  
1             0    Cherbourg  False  
2             0  Southampton   True  
3             0  Southampton  False  
4             1  Southampton   True  
..          ...          ...    ...  
886           1  Southampton   True  
887           0  Southampton   True  
888           0  Southampton  False  
889           1    Cherbourg   True  
890           1   Queenstown   True  

[891 rows x 11 columns]

In [19]:
onehot_encoder = OneHotEncoder(sparse=False)
encoded_features = onehot_encoder.fit_transform(df[['sex']])
df= pd.concat([df, pd.DataFrame(encoded_features, columns=['female', 'male'])], axis=1)
df.drop(columns=['sex'], inplace=True)
df

survived  pclass        age  sibsp  parch     fare    who  adult_male  \
0           0       3  22.000000      1      0   7.2500    man           1   
1           1       1  38.000000      1      0  71.2833  woman           0   
2           1       3  26.000000      0      0   7.9250  woman           0   
3           1       1  35.000000      1      0  53.1000  woman           0   
4           0       3  35.000000      0      0   8.0500    man           1   
..        ...     ...        ...    ...    ...      ...    ...         ...   
886         0       2  27.000000      0      0  13.0000    man           1   
887         1       1  19.000000      0      0  30.0000  woman           0   
888         0       3  29.699118      1      2  23.4500  woman           0   
889         1       1  26.000000      0      0  30.0000    man           1   
890         0       3  32.000000      0      0   7.7500    man           1   

     embark_town  alone  female  male  
0    Southampton  False     0.0   1.0  
1      Cherbourg  False     1.0   0.0  
2    Southampton   True     1.0   0.0  
3    Southampton  False     1.0   0.0  
4    Southampton   True     0.0   1.0  
..           ...    ...     ...   ...  
886  Southampton   True     0.0   1.0  
887  Southampton   True     1.0   0.0  
888  Southampton  False     1.0   0.0  
889    Cherbourg   True     0.0   1.0  
890   Queenstown   True     0.0   1.0  

[891 rows x 12 columns]