In [2]:
# 创建Numpy的数组对象
# 方式1  直接通过python中的列表, 元组转换为Numpy中的ndarray
import numpy as np
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [6]:
# 方式二 直接通过一个range函数创建一个序列
import numpy as np 
data2 = np.arange(10) # 和range方法一样
print(data2)
data3 = np.arange(1,11,2)
print(data3)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [9]:
# 创建全是0的数组
import numpy as np 
data = np.zeros(10) # 模型训练, 有时候会设置所有的权重参数为0 
print(data)
# 创建二维数组 3行4列  第一个维度 行, 第二个维度 列
data2 = np.zeros((3,4))
print(data2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# 常见的属性  
# shape: 形状(3,4): 3行4列
# dtype: 元素的数据类型 int float
# ndim: 维度, 一维数组 1 二维数组 (3,4)
# size: 元素个数
data = np.array([[1,2,3],
                [4,5,6]])

print(data.shape) # (2,3)
print(data.ndim)  # 2
print(data.dtype) # int
print(data.size)  # 6

# 改变数据类型, 复制一份新的数据, 原来的数据不会改变
result = data.astype(np.float64)

print(data.dtype,result.dtype) 

# 改变形状  一维数组==> 二维数组   二维数字===> 一维数组
a = np.arange(1,25)  # 一维数组 24个元素 2
# 三维数组 (2,4,3) 两个4行3列的数组 所有的维度的数量乘积 == 元素个数
b = a.reshape(2,4,3)
print(b)

# 多维==>一维
# c = b.reshape(24)
c = b.flatten() # 压扁
print(c)

(2, 3)
2
int32
6
int32 float64
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
# 彩色图片的颜色值
# 32*64  图片的宽 32, 图片的高度 64, 通道数理:3 (r,g,b) 图片的颜色值[0,255]