In [1]:
import numpy as np 
# 创建一个2行3列的二维数组
a = np.array([[1,2,3],[4,5,6]])
# 加法操作, 原来的数组不会改变, 返回一个新的数组
b = a + 10 # a中的每个元素都和10 操作  1+10, 2+10...
print(b)
b = 10-a  # 使用10 减去a中的每个元素  10-1, 10-2...
print(b)
b = 2*a # 2乘以a中的每个元素  2*1, 2*2...
print(b)
b = 1/a # 1除以a中的每个元素 1/1,1/2,1/3...
print(b)

[[11 12 13]
 [14 15 16]]
[[9 8 7]
 [6 5 4]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [6]:
# 数组和数组之间的运算
a = np.array([1,2,3]) # 一维数组 (3,)
b = np.array([4,5,6])
c = np.array([7,8,9,10])
d = np.array([[1,2,3],[4,5,6]]) # 二维数组: (2,3)
print(a+b)  # 对应位置的元素相加 [5,7,9]
# print(a+c)  # 报错 shapes 形状不匹配
print(a+d)  # 为什么可以相加

[5 7 9]
[[2 4 6]
 [5 7 9]]


In [9]:
import numpy as np 

data = np.array([[3,5,6],[2,1,4],[3,1,9],[6,7,10],[12,14,18]])
data2 = np.array([[1,6,8],[2,7,14],[13,15,19],[61,37,45],[54,38,52]])

data3 = np.array([[[3,5,6],[2,1,4],[3,1,9],[6,7,10],[12,14,18]],
                  [[1,6,8],[2,7,14],[13,15,19],[61,37,45],[54,38,52]]])
print(data.shape)
print(data2.shape)
print(data3.shape)
# (5, 3, 2)

(5, 3)
(5, 3)
(2, 5, 3)


In [10]:
a = np.array([1,2,3])
print(a.shape) # (3,)

(3,)


In [13]:
b = np.array([[1,2,3]])    # b = np.array([[1,2,3],[1,2,3]])        # (1,3) 复制一份=> (2,3)
d = np.array([[1,2,3],[4,5,6]])  #(2,3)
print(b.shape)

(1, 3)


In [15]:
# 改变形状
c =a.flatten().reshape(1,3)
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


In [21]:
a = np.arange(1,13)
b = a.reshape(4,1,3)
c = np.arange(1,25)
d = c.reshape(4,2,3)
print(b+d)

[[[ 2  4  6]
  [ 5  7  9]]

 [[11 13 15]
  [14 16 18]]

 [[20 22 24]
  [23 25 27]]

 [[29 31 33]
  [32 34 36]]]


In [23]:
a = np.array([1,2,3])  # (3)
b = np.array([[[4,5,6],[6,7,8]],[[4,5,6],[6,7,8]]]) # (2,2,3)
print(a+b)

[[[ 5  7  9]
  [ 7  9 11]]

 [[ 5  7  9]
  [ 7  9 11]]]
