In [4]:
import numpy as np 

a = np.array([3,4,5,6,7])
# 切片操作 就是一个视图
b = a[0::2] 
print(b)
b[0]=100 # 设置b里面的第一个元素的值为100 
print(b)
print(a) 

[3 5 7]
[100   5   7]
[100   4   5   6   7]


In [12]:
# 多维数组的切片
a = np.arange(12)
a = a.reshape(2,2,3) # 2行6列
print(a)
print('='*100)
print(a[0])  # [0 1 2]
print('='*100)
# 第一个0: 取一个维度的数值
# 第二个0: 取第二个维度的数值
# 第三个 -1  取第三个维度的数字
print(a[0,0,-1]) 


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[0 1 2]
 [3 4 5]]
2
2


In [15]:
a[:,:,1::1]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
a[:,:,1::1]

In [1]:
import numpy as np 
np.array([[1,2,3],[4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
a = np.arange(1,13)
b = a.reshape(4,1,3) 
print(b)
c = np.arange(1,9)
c = c.reshape(4,2,1)
print(c)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [11]:
b+c

array([[[ 2,  3,  4],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [ 8,  9, 10]],

       [[12, 13, 14],
        [13, 14, 15]],

       [[17, 18, 19],
        [18, 19, 20]]])

In [12]:
b

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [13]:
d = b[2,:,:]

array([[7, 8, 9]])

In [ ]:
d.copy()