In [5]:
import numpy as np 

# 常见的统计方法
a = np.array([[1,2,3,4,5,6],
             [7,8,9,3,1,2]])
print(a.shape)
print(a)  #(1,2)

(2, 6)
[[1 2 3 4 5 6]
 [7 8 9 3 1 2]]


In [8]:
# 求平均值
print(a.mean())
# 求平均值 按列统计
print(a.mean(axis=0))
# 求平均值 按行统计
print(a.mean(axis=1))

4.25
[4.  5.  6.  3.5 3.  4. ]
[3.5 5. ]


In [10]:
# 求最大值对应的索引值
print(a.flatten())
print(a.argmax())

[1 2 3 4 5 6 7 8 9 3 1 2]
8


In [29]:
# 随机数的基本操作
# np.random.seed(0)

# 生成随机数
print(np.random.rand(2,3))

# 创建一个数值范围在[1,10)直接的2行3列的数组
print(np.random.randint(low=1,high=10,size=(2,3)))

# 生成均匀分布随机数，指定随机数取值范围和数组形状
a = np.random.uniform(low=-1,high=1,size=(2,3))
print(a)
print(a.mean())

# 生成人的身高的整体分布 平均生成 170  方差:4  67%  168-172
data = np.random.normal(loc=170,scale=2,size=(2000,60000))
print(data.var())
print(data.mean())
print(data.std())

[[0.93401812 0.48698372 0.22512901]
 [0.96198196 0.24419712 0.94897311]]
[[9 5 5]
 [2 4 9]]
[[-0.05600595 -0.31987465  0.5578818 ]
 [ 0.23247953 -0.21689139 -0.51770131]]
-0.053351995237457706
3.9999665154301436
170.00032217019069
1.9999916288400168


In [31]:
# 数组的内积 点积 dot procuct
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))
# 1*4+2*5+3*6

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [34]:
# 二维数组的内积
a = np.array([[1,2,3],
              [4,5,6]]) # shape:(2,3)

b = np.array([[1],
              [2],
              [3]]) # shape: (3,1)

print(np.dot(a,b))  # shape (2,1)
# 1*1 + 2*2 + 3*3 = 14
# 4*1 + 5*2 + 6*3 = 32

# print(np.dot(b,a)) # 


[[14]
 [32]]


In [35]:
# 外积 张量积
a = np.array([1,2])  # 2
b = np.array([4,5,6]) # 3
c = np.outer(a,b)
print(c)
# 1*4 = 4, 1*5=5, 1*6 =6
# 2*4 = 8, 2*5=10,2*6=12

[[ 4  5  6]
 [ 8 10 12]]


In [38]:
# 二维数组
a = np.array([[1,2,3],[4,5,6]])  # shape: (2,3)
b = a.transpose()  # shape: (3,2)
print(a,a[1,2])
print('='*100)
print(b,b[2,1])


[[1 2 3]
 [4 5 6]] 6
[[1 4]
 [2 5]
 [3 6]] 6


In [44]:
a = np.arange(24)
b = a.reshape(2,4,3) # ndim=3
print(b,b[1,0,1])
print('='*100)
# 2: 第三个维度, 0 第一个维度, 1: 第二个维度
c = b.transpose(2,0,1) # 里面的值, 代表的是维度的索引
print(c[1,1,0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 13
13
